### ISSUE TITLE
5.3 support

### ISSUE THREAD

**Issue by avxkim** [dosarkz/epay-kazkom#2]
Привет, планируется ли поддержка L5.3?

**Comment by dosarkz** [comment]
Должно работать и на Laravel 5.3. 
Опишу в readme как будет результат.

**Comment by dosarkz** [comment]
Проверил, работает.

**Comment by tokkerbaz** [comment]
а на 5,4 ??

**Comment by dosarkz** [comment]
Внес последние изменения, должно работать и на 5.4
