### ISSUE TITLE
"Email" and "appendix" are ignored in BasicAuth

### ISSUE THREAD

**Issue by kefir500** [dosarkz/epay-kazkom#4]
Is there any specific reason why the `email` and `appendix` fields are ignored when generating url via `BasicAuth`? If no, check this pull request: #3

**Comment by dosarkz** [comment]
Hi, the fields email is not ignored, but it works even without an appendix. )
I just added in request.
`  $params = http_build_query($request->only(['Signed_Order_B64','email','BackLink','PostLink', 'appendix',
            'template']));`

**Comment by kefir500** [comment]
#### Appendix

Yes, it indeed works without `appendix`, however this field could be useful for specifying the detailed description, as shown here: https://testpay.kkb.kz/doc/htm/appendix_description.html

#### Email

The `email` field is also optional, however it could be handy to automatically fill the customer's email in the e-pay form. Have you checked [this commit](https://github.com/dosarkz/epay-kazkom/pull/3/commits/18e37103310de16c1d2c8a1fd4bbfc8c44e37c55)? The `email` field is **not** passed to the `$request->merge()` function, that's why it is simply ignored when generating the url. This [pull request](https://github.com/dosarkz/epay-kazkom/pull/3) fixes the issue.

**Comment by dosarkz** [comment]
Thanks for the answer, the function `$request->merge()`  was used only for validation and the email field is not ignored in the final query `http_build_query($request->only(['Signed_Order_B64','email','BackLink','PostLink', 'appendix', 'template']))`.
Your pull request is definitely true for validation of email type.

**Comment by dosarkz** [comment]
Really the email field was not used. Thank you)
