### ISSUE TITLE
epay post link

### ISSUE THREAD

**Issue by raymayemir** [dosarkz/epay-kazkom#5]
Можете подсказать, я указал EPAY_POST_LINK 
и хочу посмотреть что приходит в ответ после оплаты (использую test mode) 
но ничего не получаю. С чем это может быть связано ? 

UPD: p/s epay теструю в production а не локально

**Comment by dosarkz** [comment]
Какая у вас версия laravel?

**Comment by raymayemir** [comment]
@dosarkz 5.4

**Comment by dosarkz** [comment]
Скачайте последнюю версию 1.0.4. 
Добавил параметр в конфигурацию
FailurePostLink | Линк для отправки неудачного результата авторизации либо информации об ошибке в магазин. 

Post link возможно не работает в тестовом режиме epay.kkb.kz. 
Можно связаться со службой поддержки qqb либо проверять в боевом режиме.

**Comment by RaiMaemirov** [comment]
@dosarkz можете подсказать как принять ответ от epay?

**Comment by RaiMaemirov** [comment]
Не могли бы вы показать пример принятия запроса от epay ? не могу разобраться, саппорт оставляет желать лучшего

**Comment by dosarkz** [comment]
В роутах создать  `Route::post('post-link',` `'EPayController@postLink');`. Данный роут должен быть доступен без авторизации. Также советую посмотреть адрес post link в боевом кабинете коммерсанта. 

```
public function postLink(Request $request)
{
 $response = $request->input('response');

            if (isset($response))
            {
                $xml =  simplexml_load_string($response);
                $xml_to_array  = json_decode(json_encode((array)$xml), TRUE);

                Log::info($xml_to_array);
             }
}
```

**Comment by RaiMaemirov** [comment]
@dosarkz Спасибо! буду разбираться.

**Comment by dosarkz** [comment]
https://testpay.kkb.kz/doc/htm/xml_response_description.html

**Comment by RaiMaemirov** [comment]
@dosarkz Вы сами пробовали в тестовом режиме получать пост линк ?
есть разница при переходе по с генерированной ссылке или отправления через форму ?

**Comment by aubakirov** [comment]
добрый день, все сделал как вы написали но даже в боевом режиме с боевыми ключами не приходят данные в postlink, в чем может быть проблема?

**Comment by dosarkz** [comment]
Добрый день. Посмотрите в кабинете ккб данный заказ, там должен быть статус post link.

**Comment by aubakirov** [comment]
Получил данные в postlink , все заработало после того как поставил исключение URI, которые должны быть исключены из проверки CSRF, в файле VerifyCsrfToken.php  
protected $except = [
        '/post-link'
    ];

**Comment by dosarkz** [comment]
На будушее советую использовать 
`Route::any('foo', function () {
    //
});`
Если вам понравилась моя разработка, ставьте лайк.
