### ISSUE TITLE
Автоматическое списание

### ISSUE THREAD

**Issue by raymayemir** [dosarkz/epay-kazkom#6]
Доброго времени суток! 

Меня интересует автоматическое списание, не мог разобраться с пакетом. Не планируете добавить метод для формирования xml и отправки на сервер epay для подтверждения оплаты ?

**Comment by dosarkz** [comment]
Добрый день. 
Если вы имеете в виду рекурентные платежи, то они присутствуют. 
https://github.com/dosarkz/epay-kazkom/blob/master/tests/PayTest.php

> Не планируете добавить метод для формирования xml и отправки на сервер epay для подтверждения оплаты ?
Есть ли документация по этому запросу?

**Comment by raymayemir** [comment]
@dosarkz эмм это круто! но я про это [https://testpay.kkb.kz/doc/htm/remote.html](url) 
или они не отличаются особо ни чем ?

**Comment by dosarkz** [comment]
Да отличаются. По поводу фунционала подтверждения и статуса платежа, думаю стоит это сделать в ближайшем будущем.

**Comment by raymayemir** [comment]
Значит придется вручную делать, спасибо за ответ
