### ISSUE TITLE
Выдает ошибку  Call to a member function sign64() on string

### ISSUE THREAD

**Issue by iperson1337** [dosarkz/epay-kazkom#7]
Когда я перехожу боевой режим Выдает ошибку  Call to a member function sign64() on string

**Comment by dosarkz** [comment]
Такое происходит в случае ввода неверных ключей в боевом режиме в config. Советую проверить путь до ключа и сам боевой ключ.

**Comment by iperson1337** [comment]
Спасибо

**Comment by dosarkz** [comment]
Ставьте лайки либо подписывайтесь. Я буду очень рад :)
